apiVersion: 1

datasources:
  - name: telemetria-industrial
    uid: telemetria-industrial
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    jsonData:
      dbName: planta
      httpMode: POST
