apiVersion: 1

datasources:
  - name: telemetria-industrial
    uid: telemetria-industrial
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: planta
    isDefault: true
    editable: true
    jsonData:
      httpMode: GET
