[agent]
  interval = "2s"
  flush_interval = "2s"
  omit_hostname = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["planta/linea1/maquina1/telemetria"]
  name_override = "maquina_industrial"
  data_format = "json"
  tag_keys = ["maquina", "linea"]
  json_string_fields = ["estado"]

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "planta"
