{
 "title": "Demo Industrial - Máquina en vivo",
 "tags": [
  "docker",
  "industrial",
  "iot",
  "workshop"
 ],
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Estado de máquina",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Estado",
     "query": "SELECT last(\"estado_codigo\") FROM \"maquina_industrial\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Producción actual",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:pzs/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Piezas por minuto",
     "query": "SELECT last(\"piezas_por_minuto\") FROM \"maquina_industrial\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Velocidad del motor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RPM",
     "query": "SELECT last(\"rpm\") FROM \"maquina_industrial\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Presión hidráulica",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix:bar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Presión",
     "query": "SELECT last(\"presion_bar\") FROM \"maquina_industrial\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Temperatura del motor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperatura motor",
     "query": "SELECT \"temperatura_motor\" FROM \"maquina_industrial\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Vibración del equipo",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "suffix:mm/s" } },
   "targets": [
    {
     "alias": "Vibración",
     "query": "SELECT \"vibracion_mm_s\" FROM \"maquina_industrial\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Producción y velocidad normalizada",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Piezas/min",
     "query": "SELECT \"piezas_por_minuto\" FROM \"maquina_industrial\" WHERE $timeFilter"
    },
    {
     "alias": "RPM / 40",
     "query": "SELECT \"rpm\" / 40 FROM \"maquina_industrial\" WHERE $timeFilter"
    }
   ]
  }
 ]
}